[env:waveshare_esp32s3_touch_lcd_28]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Flash: 16MB QIO
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; PSRAM: 8MB OPI
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_CONF_SKIP
    -DLV_FONT_MONTSERRAT_32=1

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

lib_deps =
    lvgl/lvgl@^9.2.0
    adafruit/Adafruit BMP3XX Library@^2.1.5
    adafruit/Adafruit Unified Sensor@^1.1.14
    h2zero/NimBLE-Arduino@^2.1.0
